DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  creation_date TIMESTAMP,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  completed_date TIMESTAMP DEFAULT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  list_id INTEGER REFERENCES lists(id) ON DELETE CASCADE NOT NULL, 
  due_date DATE DEFAULT null
);
